# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chameleon Web Controller
email: your-email@domain.com
description: > # A node framework for setting up second screen experience.

baseurl: "http://devine-davies.github.io/chameleon-web-controller" # the subpath of your site, e.g. /blog
url: "http://devine-davies.github.io/chameleon-web-controller" # the base hostname & protocol for your site

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Permalinks
permalink: /:categories/:title.
# permalink:        pretty

# Server
# destination:      _gh_pages
# host:             127.0.0.1
# port:             9001
# baseurl:          /
# encoding:         UTF-8