# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chameleon Web Controller
description: > # A node framework for setting up second screen experience.
# url: "http://devine-davies.github.io" # the base hostname & protocol for your site
# baseurl: "/chameleon-web-controller" # the subpath of your site, e.g. /blog

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

email: rhysdevine@gmail.com
twitter_username: Devine-Davies
github_username:  Devine-Davies

# Build settings
markdown: kramdown
excerpt_separator : <!--more-->
encoding: UTF-8
# Server
# destination:      _gh_pages
# host:             127.0.0.1
# port:             9001
# baseurl:          /

# Permalinks
permalink: /:categories/:title.
# permalink:        pretty
